services:
  - type: web
    name: comphone-service-app # คุณสามารถเปลี่ยนชื่อนี้ได้
    env: python
    plan: free # หรือแผนบริการอื่นที่คุณเลือก
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # แนะนำให้ระบุเวอร์ชัน Python
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: "False" # ตั้งเป็น False เสมอเมื่อใช้งานจริง
      - key: GOOGLE_CLIENT_SECRETS_JSON
        sync: false # ตั้งค่านี้ใน Dashboard ของ Render โดยตรง
      - key: GOOGLE_TOKEN_JSON
        sync: false # ตั้งค่านี้ใน Dashboard ของ Render โดยตรง
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LIFF_ID_FORM
        sync: false
      - key: LINE_ADMIN_GROUP_ID
        sync: false
      - key: LINE_TECHNICIAN_GROUP_ID
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true # ให้ Render สร้าง Secret Key ให้โดยอัตโนมัติ
