"""Add menu_permissions to User model

Revision ID: 52bf5aec0f99
Revises: bd8e2453d8f3
Create Date: 2025-09-06 07:34:43.840914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bf5aec0f99'
down_revision = 'bd8e2453d8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_permissions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('menu_permissions')

    # ### end Alembic commands ###
